# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55162e935fcad1e6d4e58502507a46ffbcf45f72abb19595419a7577406c48536b39c75fbcb4e9bd057f74b757d98804dc859e2d4f1b1fcb7ee5cf3f15c4b4e2

test:
  secret_key_base: afe2fad96148a363aa507cab727053e7b3a5e762e0960cf4c4e60c06d2467d5af80a675422a3417a7c425aca081deb1de799f4ab11b9a5f97f3d154a71ae0908

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
